feign:
  hystrix:
    enabled: true

hystrix:
  share-security-context: true

management:
  security:
    roles: ADMIN
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
spring:
  application:
    name: service
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  jackson:
    serialization.write_dates_as_timestamps: false
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

server:
  session:
    cookie:
      http-only: true

info:
  project:
    version: #project.version#

mimiron:
  # By default CORS is disabled. Uncomment to enable.
  #cors:
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  swagger:
    default-include-pattern: /api/.*
    title: service API
    description: service API documentation
    version: ${info.project.version}
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
  ribbon:
    display-on-active-profiles: dev
