spring:
  profiles:
    active: dev
    include: swagger
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: localhost
      port: 8500
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./mimiron-uaa/target/h2db/db/uaa;DB_CLOSE_DELAY=-1
    username: uaa
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
  mail:
    host: smtp.163.com
    port: 25
    username: mimiron_service@163.com
    password: 13671240120
  messages:
    cache-seconds: 1
  thymeleaf:
    cache: false
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 9999

mimiron:
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization"
    allow-credentials: true
    max-age: 1800
  security:
    client-authorization:
      client-id: internal
      client-secret: internal
  mail: # specific Mimiron mail property, for standard properties see MailProperties
    from: mimiron_service@163.com
    base-url: http://127.0.0.1:9999

uaa:
  key-store:
    name: keystore.jks
    password: password
    alias: selfsigned
  web-client-configuration:
    # Access Token is valid for 5 mins
    access-token-validity-in-seconds: 300
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
    client-id: web_app
    secret: changeit
